//
// Created by adarm on 9/15/2022.
//

#ifndef PEMINJAMANBUKUUSINGCLION_KONSTANTA_H
#define PEMINJAMANBUKUUSINGCLION_KONSTANTA_H

#define MAX_ID 10
#define MAX_NAMA 40
#define MAX_STRUCT 50

#endif //PEMINJAMANBUKUUSINGCLION_KONSTANTA_H
